server:
  port: 8084

spring:
  application:
    name: importing-bill-service

  datasource:
    url: jdbc:mysql://localhost:3306/importing_bill_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

services:
  supplier:
    url: http://localhost:8083
  costume:
    url: http://localhost:8082

logging:
  level:
    com.costumestore: DEBUG
